### ISSUE TITLE
custom.txt and ignore,txt MD5 checksum does not work

### ISSUE THREAD

**Issue by Chris-git-000001** [ScriptTiger/Unified-Hosts-AutoUpdate#10]
I installed the script along with an ignore.txt file.  When I looked at the hosts file, the lines for the MD5 checksum for ignore list and custom list is blank.  After looking at the code it looks like the first "for" needs a "delims=" since for uses space a the standard delimiter (otherwise you only get the first 2 characters of the checksum.)  Also certutil is case sensitive when selecting hash type ("MD5" needed) so the lines should be:
for /f "delims=" %%0 in ('certutil -hashfile "%IGNORE%" MD5 ^| findstr /v :') do set NEWIGNORE=%%0

and:
for /f "delims=" %%0 in ('certutil -hashfile "%CUSTOM%" MD5 ^| findstr /v :') do set NEWCUSTOM=%%0

**Comment by ScriptTiger** [comment]
Greetings and thank you for your feedback! Would you mind letting us know a bit about the Windows system you're running, like version, architecture (32-bit, 64-bit), and anything you else you might think is unique about your system, such as any installations that may have replaced the original certutil with another? The output you are describing deviates from my own. Would you mind running a test for me real quick? Just create a new file, text file, image file, anything, and then run this command on that file:

`certutil -hashfile C:\<file location>`

Once it runs, please copy and paste the results here or take a screenshot so I have a better idea of how your output differs. My current script assumes the following format:

```
SHA1 hash of C:\<file>:
a94a8fe5ccb19ba61c4c0873d391e987982fbbd3
CertUtil: -hashfile command completed successfully.
```

As you can see, there are no spaces on the hash line in my particular output and I am curious if anything else deviates. From your suggestions it sounds like your output is more similar to Linux output that groups the hash in 2-character units like this:

`a9 4a 8f e5 cc b1 9b a6 1c 4c 08 73 d3 91 e9 87 98 2f bb d3`

Is your output similar to that? Would you know how to check your certutil to see if it has been replaced by a GNU utility? The case sensitivity is also non-standard, so thank you for also bringing that up. Once we figure out what's happening here we'll patch it all at the same time.

I would also like to make a note for anyone that may be following this that the script was designed to allow for no hashes and can still run perfectly fine without them, it just eliminates unnecessary overwrites of duplicate information.

**Comment by Chris-git-000001** [comment]
I am using Windows 7 x64.  I think I am using the built-in certutil and nothing has overwritten it.  The details properties page has a Microsoft copyright and is file version 6.1.7601.18151 which is Windows 7 style versioning.

I grabbed a copy of my ignore.txt and ran the hashfile command.  Here is the output:
```
SHA1 hash of file C:\ignore.txt:
d1 e3 f4 45 79 83 bb 7a 59 79 62 6b 53 ac 43 29 3b f4 8c b4
CertUtil: -hashfile command completed successfully.
```

This is the thread I found that mentions the hash type must be uppercase (and the output shows groups like mine)
[https://social.technet.microsoft.com/Forums/en-US/4c854b85-bacc-4ffb-a9aa-fd2ed4f5eafa/certutil-hashfile-md5?forum=winservergen](url)

**Comment by Chris-git-000001** [comment]
Here are the md5 outputs in lower and upper case:
C:\>certutil -hashfile C:\ignore.txt md5
CertUtil: -hashfile command FAILED: 0xd00000bb (-805306181)
CertUtil: WsResetMetadata

C:\>certutil -hashfile C:\ignore.txt MD5
MD5 hash of file C:\ignore.txt:
9c 94 67 99 bc 20 b0 b8 3b ff cd 3b 9d 1c 1f 2d
CertUtil: -hashfile command completed successfully.

I did try on two different Windows 7 x64 PCs with the same results (but I could have installed the same program both places if something did change certutil)

**Comment by ScriptTiger** [comment]
No worries, I am totally with you and am always looking to extend compatibility in any way I can. I have just pushed an update with changes to account for what you've told me, so let me know what you think when you have time. Also, just another point of curiosity, what regional/locale setup is your system using, like default language and/or country settings?

**Comment by Chris-git-000001** [comment]
United States English

**Comment by Chris-git-000001** [comment]
The hashes are working in the new script.  Thanks!
