### ISSUE TITLE
No internet after restart for minutes

### ISSUE THREAD

**Issue by xKeiro** [ScriptTiger/Unified-Hosts-AutoUpdate#12]
Ever since I used Unified Hosts AtuoUpdate whenever I turn on my PC for minutes I won't have internet, the only thing that seems to help if I run the windows network troubleshooter, even though it says it didn't find anything wrong when it finishes I finally able to use the internet.

Why is this happening, can I do something about it?

**Comment by ScriptTiger** [comment]
It's possible this is related to the client cache issue mentioned in https://github.com/ScriptTiger/Unified-Hosts-AutoUpdate/issues/5. It's common for affected users to have issues immediately after starting up their machine. This script will include compression options in the future to resolve this, but for now can you manually test one of  the compressed hosts list formats from the below link and let us know if it works for you?
https://scripttiger.github.io/alts/

**Comment by xKeiro** [comment]
Replaced host file with the a compressed one, restarted PC twice, seems like it fixed the issue!

**Comment by ScriptTiger** [comment]
Glad to hear! There are a bundle of new options I would like to add in the coming months and they must all first be properly tested in combination with each other before rolling them out, as well as double-checking to make sure as many critical flaws have been removed as possible from the current script. This one is definitely towards the top of the priority list though, so have no fear, be patient, and thanks for your interest in the project!

**Comment by ScriptTiger** [comment]
Also, if you decide to switch to updating the hosts manually in the meantime, please remember to either delete the scheduled task manually or by running the script so it doesn't overwrite it. And feel free to "watch" this repo to get notifications of updates so you know as soon as the feature you're waiting for is implemented. When updates are made to this repo, all you have to do is run the script you already have on your machine, either manually or automatically, and it is capable of updating itself to the latest version.

**Comment by ScriptTiger** [comment]
@xKeiro, check out the new compression level feature in my script, this should allow you to automatically update with my script and it compresses it for you.

**Comment by xKeiro** [comment]
It works! Cheers! :)
