### ISSUE TITLE
reset the hosts script

### ISSUE THREAD

**Issue by abhijithvijayan** [ScriptTiger/Unified-Hosts-AutoUpdate#15]
could you add another script to reset the hosts file to windows default. I found this awesome tool from this [page](https://github.com/HostsTools/Windows) that does that impressively.

![choose_2018-07-23_15-29-14](https://user-images.githubusercontent.com/34790378/43070362-45be8bd8-8e8d-11e8-8541-790d3300b28a.png)

Choosing option 5 resets the hosts to the windows default
Choosing option 4 resets the hosts to the version before updating the hosts file with that tool

**Comment by ScriptTiger** [comment]
My script doesn't replace the hosts file and my script also comes with a removal tool, so this is not really related to this project. You can edit your hosts file however you want before and after you use my script and my script will not change anything, it only adds/updates the hosts file entries from Steven Black, and removes them if you wish. It doesn't touch anything else in the hosts file, so you can actually use other tools at the same time with my script.

For resetting your hosts file to "default," it's best to do this manually:
https://support.microsoft.com/en-us/help/972034/how-to-reset-the-hosts-file-back-to-the-default

**Comment by abhijithvijayan** [comment]
Thanks

**Comment by ScriptTiger** [comment]
@abhijithvijayan, are you mentioning this because you don't know how to remove the Unified Hosts entries with the script?

**Comment by abhijithvijayan** [comment]
I know how to reset everything manually. But I always prefer use of script.

**Comment by ScriptTiger** [comment]
Sure.  After you have installed the hosts entries with my script, you can run it again any time you want and remove it by doing the following prompts:
You currently have a scheduled task already in place
Would you like to keep it? N
The Unified Hosts is already installed in your local hosts file
Would you like to continue to update it? N
Would you like to remove the Unified Hosts from your local hosts file? Y

**Comment by ScriptTiger** [comment]
@abhijithvijayan, does that help? Is that what you were talking about?
