### ISSUE TITLE
Hosts file does not open if "y" selected but UserChoice registry key has not been set

### ISSUE THREAD

**Issue by Chris-git-000001** [ScriptTiger/Unified-Hosts-AutoUpdate#16]
The last question the script asks is if I want to open my hosts file.  I have never right-clicked on a text file and set a user choice for default program for .txt since I use notepad normally and that hapens automatically in Windows 7.  Because of that, the logic fails and instead the last program in the list created by the 'ftype' command opens (in my case Zoom Player.)  If I right-click on a .txt file and choose notepad as my default, after that it works.  The first reg query should probably check errorlevel and bail out if the key doesn't exist and open with notepad there.  I do like the logic other than that in case the user uses notepad++ or something like that in place of notepad.  I tested with 4 Windows 7 x64 PCs.

**Comment by Chris-git-000001** [comment]
This seems to work:

````
choice.exe /m "Would you like to open your current hosts file before exiting?"
if !errorlevel!==1 (
	reg query HKCU\Software\Microsoft\Windows\CurrentVersion\Explorer\FileExts\.txt\UserChoice /v PROGID
	if !errorlevel!==0 (
		for /f "tokens=3" %%a in (
			'reg query HKCU\Software\Microsoft\Windows\CurrentVersion\Explorer\FileExts\.txt\UserChoice /v PROGID'
		) do set PROGID=%%a
		for /f "tokens=2 delims==" %%a in (
			'ftype !PROGID!'
		) do set CMDVIEWTEXT=%%a
		for /f "tokens=* usebackq" %%a in (
			`echo "!CMDVIEWTEXT:%%1=%HOSTS%!"`
		) do (
			start "" %%~a
		)
	) else start notepad %HOSTS%
)
````

**Comment by ScriptTiger** [comment]
Nice catch. I'm open to a PR for this if you'd like.

**Comment by Chris-git-000001** [comment]
Yes, please do so.

**Comment by ScriptTiger** [comment]
Done!
https://github.com/ScriptTiger/Unified-Hosts-AutoUpdate/commit/b9be9bdd7b9bea61ac1dfcc07f6ab5771b179a92
Thanks, again, for your feedback!

**Comment by Chris-git-000001** [comment]
The hosts file open properly in Notepad now.  Thanks.
