### ISSUE TITLE
ignore list ignored

### ISSUE THREAD

**Issue by ghost** [ScriptTiger/Unified-Hosts-AutoUpdate#18]
I have in my ignore.txt:
.4chan.org
but somehow, even after updating multiple times, when I open my hosts file, I still see "0.0.0.0 4chan.org"
Am I doing something wrong? should I make two entries in the ignore list, one with and one without the dot at the start?

**Comment by ScriptTiger** [comment]
Right now the ignore list works on literal expressions. If you want to ignore a specific line, just put that line verbatim in the ignore.txt like this:

`0.0.0.0 4chan.org`

Right now you have `.4chan.org`, with a period in front. This will ignore all 4chan subdomains, but it will not ignore 4chan itself. If you want to ignore 4chan and all of its subdomains, use this:

```
0.0.0.0 4chan.org
.4chan.org
```

`0.0.0.0 4chan.org` will ignore the 4chan.org domain and `.4chan.org` will ignore all subdomains of 4chan.org.

I have been toying with the idea of using regular expressions instead, but for now literals seem to be easier for most people to work with. After rereading the readme though I can understand why this might be confusing, as I don't include an example with `0.0.0.0` in front. I will update the readme shortly. Any other suggestions you might have are also welcome.

**Comment by ghost** [comment]
> Right now you have .4chan.org, with a period in front. This will block all 4chan subdomains

but I put it in the ignore list, not in the custom list. My intention was to **UN**block 4chan.

**Comment by ScriptTiger** [comment]
My apologies, I meant "ignore" not "block." I edited my last comment accordingly.

**Comment by ghost** [comment]
Thank you!
