### ISSUE TITLE
Option to Whitelist a domain

### ISSUE THREAD

**Issue by qarqun** [ScriptTiger/Unified-Hosts-AutoUpdate#2]
Hi,
Any option to whitelist a certain domain.
I only saw a blacklist option.

Thanks.

**Comment by ScriptTiger** [comment]
Not at the moment. I'll keep this issue open though and resolve that in due time.

**Comment by ScriptTiger** [comment]
Realizing this script is basically useless without a whitelist for those like yourself that need to remove certain entries, I would also just like to assure you this issue is currently the highest priority for this project at the moment. I had honestly never thought of it before as the goal was just a means of updating, but this is definitely an important point and will be resolved shortly. So I seriously apologize for that oversight on my part.

**Comment by ScriptTiger** [comment]
I added an ignore list. The next time you manually or automatically run your script, it will update itself with the new changes and create a fresh copy of the new ignore file in the same directory. I also added some further information in the README. Let me know what you think!

**Comment by qarqun** [comment]
Nice man!

Feedback:

1. The ignore list is fine and working without any issue.
2. It is best if you can add 'blacklist' file also. Custom domain to be include in HOST file can be added directly in this file.

>  The next time you manually or automatically run your script, it will update itself with the new changes and create a fresh copy of the new ignore file in the same directory.

The script was updated. However we need to manually close current running script and run again the newly updated script for an up-to-date script execution.

It best if can automatically close current and launch updated script on the fly.
I also wondering how the same thing happen if the script was auto run using task scheduler.

Again... thanks for your awesome script. really appreciate it.

**Comment by ScriptTiger** [comment]
The script should already restart itself within the same window so you don't notice that it is already doing it. If it is not doing that, then that is a problem.

Edit your script and copy and paste this line to anywhere in your script on a new line:

rem THIS IS A TEST!!!!

Now try deleting your "VERSION" file and run the script again. Is the line you copied and pasted still there?

**Comment by qarqun** [comment]
> The script should already restart itself within the same window so you don't notice that it is already doing it. If it is not doing that, then that is a problem.
> 
> Edit your script and copy and paste this line to anywhere in your script on a new line:
> 
> rem THIS IS A TEST!!!!
> 
> Now try deleting your "VERSION" file and run the script again. Is the line you copied and pasted still there?

The line is not there.

As i said , the code is updated, But it not restarted itself within the same window.. i have to manually close and run again then the new code works. i have tried twice with the same result.

**Comment by ScriptTiger** [comment]
Hmm. How do you know it is the same? Does the script break or stop working after it updates? The way I make it update, I am not sure how it is possible it is the same code because the old code will not exist anymore when the script runs itself again and it can only read the new code. Can you tell me what you are looking for to tell you that the script is the same or not?

**Comment by ScriptTiger** [comment]
Can you try to replace your current script with this one and tell me what happens?

[UpdateDebug.zip](https://github.com/ScriptTiger/Unified-Hosts-AutoUpdate/files/1215372/UpdateDebug.zip)

**Comment by qarqun** [comment]
> Hmm. How do you know it is the same? Does the script break or stop working after it updates? The way I make it update, I am not sure how it is possible it is the same code because the old code will not exist anymore when the script runs itself again and it can only read the new code. Can you tell me what you are looking for to tell you that the script is the same or not?

It's the same...  (note: i'm running Windows 10 Home 64-bit)
i still have the v1.1 script (the one without schedule task script yet)
Once i run the script, it will said....A new script update is available! then it will......Updating script...
To confirm, while the CMD windows still open, i open with notepad the Hosts_Update.cmd file  and verified the code is the latest from existing...it have the create schedule task script.. i open VERSION file and confirm the version is 1.3...also ignore.txt file created.
however, if the 'running' script already updated to the latest version, supposed it should appear
"You don't yet have a scheduled task to automatically update daily
Would you like to create a scheduled task now? [Y,N]? "

BUT this doesn't happen... i need to close current cmd window and run the script again... then the latest code will in action...

Refer output below.. i hope this will make u understand..

from v1.1 (then auto update to v1.3)
```
Checking for script updates...
A new script update is available!
Updating script...
The Unified Hosts is already installed in your local hosts file
Would you like to continue to update it? [Y,N]?Y
Checking for Unified Hosts updates...
You already have the latest version.
Would you like to update anyway? [Y,N]?Y
Your current preset is to use the following Unified Hosts:
https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts
Would you like to just stick with that? [Y,N]?Y
Updating the hosts file...
Your Unified Hosts has been updated
Flushing local DNS cache...
Would you like to open your current hosts file before exiting? [Y,N]?
```

from v1.3 (run again the new script)

```
Checking for script updates...
The Unified Hosts is already installed in your local hosts file
Would you like to continue to update it? [Y,N]?Y
Checking for Unified Hosts updates...
You already have the latest version.
Would you like to update anyway? [Y,N]?Y
Your current preset is to use the following Unified Hosts:
https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts
Would you like to just stick with that? [Y,N]?Y
Updating the hosts file...
Your Unified Hosts has been updated
Flushing local DNS cache...
You don't yet have a scheduled task to automatically update daily
Would you like to create a scheduled task now? [Y,N]?Y
SUCCESS: The scheduled task "Unified Hosts AutoUpdate" has successfully been created.
Would you like to open your current hosts file before exiting? [Y,N]?
```

**Comment by ScriptTiger** [comment]
Thank you for your thorough feedback! I have just pushed an update to address this. Feel free to test it once again by updating from 1.1 to the new 1.5 and let me know if this addresses the problem you were having.
