### ISSUE TITLE
custom.txt issue

### ISSUE THREAD

**Issue by EPiC-APOC** [ScriptTiger/Unified-Hosts-AutoUpdate#26]
(running Unified-Hosts-AutoUpdate with Windows 10 Pro x64)

When I add analytics.ff.avast.com to 'custom.txt' it does not get processed.
I used: 0.0.0.0 analytics.ff.avast.com

all other lines do get processed, for instance: 0.0.0.0 adservice.google.com

With kind regards

**Comment by ScriptTiger** [comment]
Can you manually copy and paste the following lines to the bottom of your hosts file?

```
# Test start
0.0.0.0 analytics.ff.avast.com
# Test end
```

Just as a quick reference, your hosts file can be quickly edited by running your favorite text editor with administrative privileges and accessing the hosts file at the following location:
`%SYSTEMROOT%\System32\drivers\etc\hosts`

Then save your hosts files and wait a few seconds. Re-open your hosts file and copy and paste the bottom lines of your hosts file here, starting with the `# Test start` line and ending with the `# Test end` line.

My suspicion is that another application is scanning your hosts file for changes and independently editing/"protecting" it by itself.

**Comment by EPiC-APOC** [comment]
Will do, but my other lines do get processed though, just this one line seem to get skipped somehow for some reason, really weird

**Comment by EPiC-APOC** [comment]
if I copypaste these line, save and close notepad+ and then re-open hosts `0.0.0.0 analytics.ff.avast.com` is gone. I guess AVG Free Antivirus is doing this. Thank you, now I know why this seems to happen. Thank you very much, so it is NOT an issue. 

With kind regards

**Comment by ScriptTiger** [comment]
No worries. If you find the solution to this though, please drop a note here. AVG is a subsidiary of Avast, so it definitely makes sense. Many people have had to make exceptions for the script with their antivirus, but I'm not sure if that would work in this case. This sounds more like a "file protection" issue and I think AVG runs that separately. I would definitely be interested to hear back if you get this figured out on your end.

**Comment by EPiC-APOC** [comment]
**workaround:**
Host file modification are protected by Self protection module component and during the installation of AVG itself. ("Menu->Troubleshooting->Enable self protection module ; choosing disable FIXED this)

**Comment by ScriptTiger** [comment]
Nice, thanks for the follow-up!
