### ISSUE TITLE
The Official Chocolatey Package!

### ISSUE THREAD

**Issue by ScriptTiger** [ScriptTiger/Unified-Hosts-AutoUpdate#29]
I just found out this project has an official Chocolatey package! It sounds pretty cool, but I don't use Chocolatey personally and don't have any experience with it. I would really like to promote this in the future though if it's legit. Can someone verify this package for me and let me know their findings?

P.S.: For those that don't know, Chocolatey is a package manager for Windows, similar to the Linux package managers. `choco install unified-hosts-autoupdate` will install my script on Windows similar to how you do `apt-get install` on Linux. So if you don't have Chocolatey now but you're now thinking about getting it because it sounds cool, try installing the `unified-hosts-autoupdate` first and let me know how it goes.

**Comment by ohadschn** [comment]
IMO there is no point in using Chocolatey as long as you have your own independent update mechanism (script auto update). It will just be confusing as choco would say you have version `x` where in fact auto update kicked in at some point and updated you to version `y`.

I would also prefer to install a package you managed,not some unknown third party. I believe the proper of doing this would be:
1. Set up CI (e.g. Azure DevOps) to generate proper GitHub releases from your commits
1. Add a step to the CI that publishes new versions to Chocolatey
1. Replace the existing script's auto update mechanism with a mechanism that leverages Chocolatey

**Comment by ScriptTiger** [comment]
I noticed the versioning, too. I just checked (https://chocolatey.org/packages/unified-hosts-autoupdate/1.28) and it's already updated to the new version I just pushed, but according to @chtof's repo (https://github.com/chtof/chocolatey-packages/tree/master/automatic/unified-hosts-autoupdate) it was updated about 5 hours after I updated mine, so I think it's a manual process on their end. They do maintain a number of packages there, but even if their queue was delayed it wouldn't be delayed 5 hours if it was automated.

I also checked the @chtof's commit (https://github.com/chtof/chocolatey-packages/commit/fe276de1b2ab9cbc980790694f2e9baaca44bc38#diff-bfe4d484f073ab4802558b67f0d77feb) as well as the package VERIFICATION.txt (https://chocolatey.org/packages/unified-hosts-autoupdate/1.28#files) and the SHA256 checksums for my repo master.zip (https://github.com/ScriptTiger/Unified-Hosts-AutoUpdate/archive/master.zip) and they all match.

The one thing I don't know about is the VirtualHere USB Client being included with the package. Obviously connecting unknown remote USB devices to one's computer sounds pretty dangerous. @chtof, can you explain some of these things in more detail?

**Comment by ohadschn** [comment]
I'm sure @chtof 's intentions are good, but seeing as you own the repo, I think it makes sense for you to set up the CI, versioning, and push to Chocolatey (or grant @chtof permissions to do it for you). Regardless, as I mentioned the way version updates work now, IMHO Chocolatey does more harm than good (version confusion and competing update mechanisms).

**Comment by ScriptTiger** [comment]
Agreed. I don't have any intention of integrating with Chocolatey , but I am happy you revisited this because I would like to know what VirtualHere is being used for. Obviously if my script is being packaged as a trojan with malicious intent, that's something we need to put an end to ASAP.

**Comment by chtof** [comment]
Hello, my update scripts are automatically launched every 8 hours from the AppVeyor platform.
The targeted URL are always the same so when you release a new version (the checksum of your file changes), it can takes until 8 hours to submit the new version. And if someone try to install or upgrade this package between the moment you have released the package and the moment the update script is triggered, the installation fails because the checksum has changed. I don't know if it's a real problem because:
- A lot of installer links are always the same (doesn't contain a version number).
- "choco update all" allow to upgrade all packages. This command go to the next package when an update failed. So the failed package will be successfully updated the next time the upgrade command will be launched.
- Even if you trigger yourself the update script, 1 to 2 hours will be necessary by the Chocolatey platform to check automatically the new version (yes, better than to wait until 8 hours).
Should I understand you are looking for a solution to deploy faster a new version in the Chocolatey repository?

**Comment by chtof** [comment]
Also, if you have find virtualhere client in your package, it's a mistake. Could you tell me where you have seen this software in your one?

**Comment by chtof** [comment]
Also, @ScriptTiger Chocolatey packages and all binaries are checked by VirusTotal.
As I maintain also the Chocolatey packages for virtualhere, it's really possible I made a mistake but I need more information to correct that (where have you find virtualhere?).

**Comment by ScriptTiger** [comment]
Oh, okay. Never mind about the VirtualHere. From what you are saying, I think I was mistaken because your VirtualHere was updated at the same time in the same commit because of the way your intervals work, so I got confused there. Sorry about that.

Otherwise, I think 8 hours is acceptable. As I said, I don't plan on maintaining anything for it because, as @ohadschn already said, my script already manages itself. So if people trust me and only me for whatever reason, they can do so and everything keeps working fine. However, I don't mind it popping up in the Chocolatey package listings for extra exposure to people using that. However people prefer to consume their software is fine with me, as long as they trust you as the maintainer. As far as I can see everything looks legit, so it looks cool to me.

**Comment by ScriptTiger** [comment]
@chtof, I deleted my early comments of suspicion, as I don't want later readers to think ill of your product simply because I didn't understand your update cycle. My apologies again and thank you a lot for replying and explaining!

**Comment by ohadschn** [comment]
Let me just reiterate my opinion that the current state is not so good. You have the Chocolatey package at version `x`, but you have the script in version `y` (because it updates itself). So the versions don't match and you have two separate, competing update mechanisms.

IMHO, either you support Chocolatey all they way, or you don't support it at all (because your own mechanism replaces it).

**Comment by ScriptTiger** [comment]
As it requires third-party binaries, I can't support it at all as it deviates from the premise of this project, and that's my official stance. However, I do appreciate @chtof's intentions and interest in this project and it has caught my attention, so I will be keeping an eye on how things are handled there.

**Comment by ohadschn** [comment]
I guess you could always check whether the script has been installed via your update mechanism, or Chocolatey...

**Comment by ScriptTiger** [comment]
Thanks for everybody's input on this! I'll close this issue for now, but, as I said, keeping an eye on this.

**Comment by chtof** [comment]
@ohadschn The Chocolatey package get the master.zip package and from this package, Hosts_update.cmd is installed to allow to execute this command whatever your current directory is ("PATH"). At the end of the installation, the user is informed by a message "Run the Hosts_Update.cmd script to begin to use "Unified Hosts AutoUpdate"". The master.zip package contains only Hosts_Update.cmd and text files.
In other words, the Chocolatey package unified-hosts-autoupdate doesn't handle host file updates in the same way an user download master.zip and has to run Hosts_Update.cmd script. So, with Chocolatey, you can just have a script until 8 hours older than the new version. But the unified-hosts-autoupdate manages itself so it can be considerate as a false problem (the last time an user has launched the "official" Hosts_Update.cmd script can be a long time ago and if it is from the Chocolatey package, the Hosts_Update.cmd will be also able to be updated as it is the same script who requires an user interaction in both cases).
The mechanism are the same. The Chocolatey package is only another way to install the script.
On another point ("However people prefer to consume their software is fine with me, as long as they trust you as the maintainer."), there are currently more of 7.400 Chocolatey packages, also this link can make you feel more comfortable https://chocolatey.org/docs/security#chocolateyorg-packages
If a Chocolatey package is no longer maintained, a request can be sent to ask for a new maintainer (but here, the script is also able to manage itself).

**Comment by ohadschn** [comment]
The Chocolatey package might be updated on the Chocolatey gallery, but out of the box there is no mechanism that will auto update it on the user's machine.

Imagine this scenario:
1. I install `unified-hosts-autoupdate` version 1.28 via Chocolatey
1. After some time, 1.29 gets released
1. Your CI (AppVeyor) creates a 1.29 Chocolatey package (but I never update to it)
1. I run the script, which automatically updates itself to version 1.29

At this point, my script is 1.29 but Chocolatey says I'm on 1.28 (e.g. when I run `choco list --local-only`).
This is a bad state, and this is what I mean by two separate mechanisms:
1. The script can update itself
1. Chocolatey can update its packages

**Comment by chtof** [comment]
I understand. Others Chocolatey packages like Chrome, Firefox, FileZilla, Notepad++ and many others are able to update themselves. I think almost Chocolatey users knows their software can be updated themselves or by Chocolatey upgrades. In the first case:
- Either they guess a little offset can exists between the 2 versions (if they compare the versions during the period between the time the new version is released and the time the new Chocolatey version is released).
- Or they don't compare the Chocolatey version with the one of the developer site
- Or they understand there is a version for a Chocolatey package and a version for the software.

Is it a real problem to have this little difference of version (taking into account there is a version for the Chocolatey package and a version for the script) ?
It's possible to add a warning about that in the description of this Chocolatey package for example.
Also nothing is perfect. However, I think the Chocolatey package allows to install quickly, easily this script (and scanned by VirusTotal), in other words, there are also a few advantages.
Maybe we can compare this kind of deployment as in organization. I have seen we can add an "X" at the end of the version in the VERSION file to block automatic upgrades of the script, it can be also a solution if it's really a problem to have a little offset between the script version and the Chocolatey package version.

**Comment by ScriptTiger** [comment]
I think you both bring up a good point about a distinction between Windows and Linux. Many Windows apps do have automatic update mechanisms, while their Linux counterparts purposely don't because they must wait for the available package from their package repository because their dev teams aren't going to personally maintain packages for every distro, so they rely on distributed maintainers in each distro to take care of it for them.

On one hand Windows has an advantage as a common platform people develop directly for, while on the other hand it was never designed with package managers in mind and may not play nice since many developers take advantage of the common platform to build individualized internal automatic update mechanisms into their apps. I don't think @chtof is doing anything wrong as a maintainer, I think @ohadschn's arguments are more fundamental towards Chocolatey itself and better addressed by someone like @ferventcoder or @gep13 as to their ideas around this "bad state" of mixed versions, whether it is something to worry about or just something that's possibly confusing, etc., etc.

Like I said, I don't think it's right putting @chtof on the spot too much because they are just using Chocolatey as it's intended. Or perhaps does Chocolatey recommend having custom builds in their packages that strip out internal app update mechanisms to better mirror the Linux model? Does the Chrome package in Chocolatey (https://chocolatey.org/packages/GoogleChrome) update itself or not? What are other people's thoughts on this?

**Comment by spirillen** [comment]
As better a program is to keep it self up to date as better it is, reply blindly on third partys for receiving important updates like the unbound (v.1.9.2 ubuntu 19| v 1.6.2 ubuntu 18) versus the very important updates in v.1.9.4, shows how bad it is to reply on package-systems alone

https://nlnetlabs.nl/projects/unbound/security-advisories/#vulnerability-in-ipsec-module

```
unbound/disco-updates,disco-security,now 1.9.0-2ubuntu0.1 amd64
```

While I have the self compiled version 1.9.6.

But the one can't rule out the other by it self, for compiling and keeping modules (linux) up to date requires skill beyond the average user and a decent insight to how software is developed and working.

So as I see this is:

\#1 is to build in a version checker, and if new version > announce an update is available.
\#2 On the chocolatey have current version -.1 ex. This script is version 1.1.2.1 then on the chokolatebar it is version 1.1.2. HOWEVER, this will requires an active maintaining from any given user, that will publish through the hot chocolate.

In this way the @ScriptTiger release will always win the competition of versions.

**Comment by ohadschn** [comment]
> #1 is to build in a version checker, and if new version > announce an update is available.

I think this makes sense - in the Chocolatey case, let the user know there is an update and let them run `choco upgrade`, rather than update the script automatically behind the scenes and creating the version discrepancy discussed above.
