### ISSUE TITLE
User Interface

### ISSUE THREAD

**Issue by ScriptTiger** [ScriptTiger/Unified-Hosts-AutoUpdate#3]
I would like to get everyone's opinion of the current interface. Currently the process is a series of yes or no questions that dynamically change depending on your current setup. I was thinking if maybe a menu might be easier? I like the yes/no setup for the first time you run it just so it can take you through everything step by step, but maybe subsequent times the yes/no might be annoying and maybe a menu to jump to specific things might be better? But then again if everyone is using it via a scheduled task, then they won't have time to find the interactive mode annoying. If the only time people are using it interactively is to do the install and uninstall, then maybe guiding users through with a yes/no series is better. Anything is possible, so just drop your comments so I can get some direction on this.

**Comment by qarqun** [comment]
I like the 'menu' idea..
You can combine the menu with interactive mode.

For example, if i have added new entry in ignore list, then i just have to launch the script and select the task from the menu without going to the process of yes/no from beginning.

**Comment by ScriptTiger** [comment]
Thanks for your feedback. Since this is a user experience issue, I'll wait for some more feedback before implementing anything. But I'll start working on some different ideas of my own maybe in other branches you can test out later.

**Comment by ghost** [comment]
I am personally happy with the interface. It does the job beautifully. If it matters I do not use the scheduled task option. I occasionally launch the script myself manually on random intervals.

**Comment by ScriptTiger** [comment]
Hosts file write operation progress output feature request:
https://github.com/ScriptTiger/Unified-Hosts-AutoUpdate/issues/20#issuecomment-426246430

**Comment by ohadschn** [comment]
Personally the current interface is good enough for me, just ran it one time, got the scheduled task and forgot about it. However a GUI could have some benefits, check out HostsMan for ideas: http://www.abelhadigital.com/hostsman/

**Comment by ScriptTiger** [comment]
Thanks for everyone's input on this. Since it seems like everyone is generally happy with the UI, I'll keep it as is for now and revisit it again later after development on the core functionality slows down.
