### ISSUE TITLE
Social block

### ISSUE THREAD

**Issue by ghost** [ScriptTiger/Unified-Hosts-AutoUpdate#32]
The social blocking filter is really cumbersome to work with, like many reddit domains are also under the tumblr list and so on. Is there a way for the script to just ask me which social media sites to whitelist? I mean when people want to block social, they usually want all of them blocked, except the one or two that they still use, so it would be great to have the option of telling the script which ones to ignore. 
Having to hunt down the entire list of convoluted domains and subdomains of the social media sites you use to add to the ignore list (and hope it actually gets ignored) is really a pain.

**Comment by ScriptTiger** [comment]
If you can think of a good way to break out the social list into smaller sub-categories that everyone can agree with, I would recommend opening issues with the curators here:

https://github.com/Sinfonietta/hostfiles
https://github.com/tiuxo/hosts

This project doesn't curate lists and pulls them directly from Steven Black's aggregate, which is the only purpose of this script and not to manage the content by any means. If the above curators agree with your ideas and split off new sub-lists, we can then perhaps talk about where to go from there and if those sub-lists should be implemented into the script as options.

**Comment by ScriptTiger** [comment]
I'm closing this since it's not actually directly related to this repo. If you have any updates for me on whether or not the curators decided to split off new categories, please open another issue and we can work through how to integrate them. But great ideas, thanks a lot, keep them coming!
