### ISSUE TITLE
Generated update scheduled task succeeds but returns result 0x1

### ISSUE THREAD

**Issue by ohadschn** [ScriptTiger/Unified-Hosts-AutoUpdate#34]
Please see:
https://stackoverflow.com/questions/18370547/windows-scheduled-task-succeeds-but-returns-result-0x1

Fix is very simple, first bullet in the highest voted answer:
https://stackoverflow.com/a/34362341/67824

> * Right click on your task > `Properties` > `Actions` > `Edit` 
> * Put ONLY the file name under 'Program/script' (no quotes) 
> * Put ONLY the directory under 'Start in' as described (again, no quotes)

So basically I suggest you create the update task like that (using `schtasks`) to begin with.

Otherwise script works great, thanks a bunch for it!

**Comment by ScriptTiger** [comment]
Nice catch! Please remove your current task and run the script again, let your script automatically update itself, and then make a new task and confirm the new one works and let me know so we can close this issue, or follow up as necessary. Thanks again!

**Comment by ohadschn** [comment]
Works great, thanks!
