### ISSUE TITLE
Error trying to open current HOSTS file before exiting

### ISSUE THREAD

**Issue by ohadschn** [ScriptTiger/Unified-Hosts-AutoUpdate#39]
> [Window Title]
> %1=C:\WINDOWS\System32\drivers\etc\hosts
> 
> [Content]
> Windows cannot find '%1=C:\WINDOWS\System32\drivers\etc\hosts'. Make sure you typed the name correctly, and then try again.
> 
> [OK]

![image](https://user-images.githubusercontent.com/8555641/71718809-0faec100-2e25-11ea-9edc-602d9392de32.png)

**Comment by ScriptTiger** [comment]
More error handling needs to be implemented to catch this and use the standard Notepad.exe in case of an error. Thanks! I'll review this later and see what I can do. PRs are always welcome, too.

**Comment by ScriptTiger** [comment]
This issue has been addressed in 1.30. Please check it out and let know if that closes out the issue for you!

**Comment by ScriptTiger** [comment]
I'm not going to close this one yet though, I still don't like defaulting to notepad when you obviously have a different preferred editor. Later I will add snooping the registry for applications that don't show in ftype (i.e. `reg query HKCR\Applications\notepad++.exe\shell\open\command`).

**Comment by ScriptTiger** [comment]
Done!

While you are testing the `/DFC` switch from your other issue (https://github.com/ScriptTiger/Unified-Hosts-AutoUpdate/issues/35) using the developmental script, please also test opening your hosts file at the end of the script.

As with the other issue, as soon as you can confirm everything in that developmental scripts works as it should, I'll go ahead and release it.

**Comment by ohadschn** [comment]
Fix works great, opens with notepad 👍

**Comment by ScriptTiger** [comment]
Hmmm... It opens with Notepad or Notepad++? From your picture, it should be opening Notepad++. Opening Notepad is just the default if nothing else works, but Notepad++ should work with 1.31. If it's not working like that, I'll keep this open and revisit it again.

**Comment by ScriptTiger** [comment]
As just stated in your other issue, all of the latest changes have been pushed in the latest release. Please pull the latest update automatically and test it again to see if Notepad++ works.

**Comment by ohadschn** [comment]
Now it opens Notepad++ 🥇
