### ISSUE TITLE
Retry improvements

### ISSUE THREAD

**Issue by ohadschn** [ScriptTiger/Unified-Hosts-AutoUpdate#44]
Regarding the Retry function:
https://github.com/ScriptTiger/Unified-Hosts-AutoUpdate/blob/8730f69ad6eb1ed70a6d31d4b853dffd9268557a/Hosts_Update.cmd#L686

1. It looks like there is no limit to the amount of retries, possibly looping forever. I think at some point (e.g. 10 retries) the script needs to give up.
1. Ideally, you would implement a simple exponential back-off strategy (or something like it), rather than wait exactly 10 seconds each time (so you would wait 10, 20, 40, 80, and then maybe cap it at 120, 120, 120, etc). This will help overcoming intermittent network issues.

**Comment by ScriptTiger** [comment]
As stated in the other issue (https://github.com/ScriptTiger/Unified-Hosts-AutoUpdate/issues/43), the script only uses the `:Download` function after the Internet connection has been verified, twice in most cases but only once for those bypassing script updates. After these checks, the script assumes the possibility of a connection, but does not make any assumptions towards the reliability of that connection, and continues to retry into perpetuity.

I have also been toying with the possibility of a retry counter, but the exponentially increasing delay is also a nice idea. I'll work on this together with the other issue and let you know what I've come up with.

**Comment by ScriptTiger** [comment]
As I stated in your other issue, I just updated it to cap at 3 retries, and added an additional incremental 30 seconds to the delay of each retry.

Let me know if this works for you. If so, I'll push it as a release.

**Comment by ohadschn** [comment]
> Added a cap of 3 retries, with incremental time delays of an additional 30 seconds each additional retry.

That's great, exponential would be even better IMHO and just as easy to implement (with a few more retries, say 10s, 20s, 40s, 80s, 160s, 320s)

**Comment by ScriptTiger** [comment]
I followed your example to the letter, exponentially increasing delays for up to 6 retries, although I don't know if you were just giving me arbitrary numbers or not.

Please test these new changes at your earliest convenience. I have also thrown a critical update into the bunch while I was working on your feature requests, so the sooner I can release this the better.

**Comment by ohadschn** [comment]
> I followed your example to the letter, exponentially increasing delays for up to 6 retries, although I don't know if you were just giving me arbitrary numbers or not.
> 
> Please test these new changes at your earliest convenience. I have also thrown a critical update into the bunch while I was working on your feature requests, so the sooner I can release this the better.

Looks great, thanks!

**Comment by ohadschn** [comment]
I do see one problem, when all retry attempts are exhausted, I don't get a `msg` error...

**Comment by ohadschn** [comment]
OK I think I know what's wrong, the script does check for the download's success, and it does set the URL, but it doesn't set the `EXIT` variable so the `:Exit` method thinks it's in the happy/success path.

This seems to be the case in all 5 places where `if !DOWNLOAD!==0` is checked.

**Comment by ScriptTiger** [comment]
DOH! I had actually implemented a `:Failed_Download` function previously, but forget to link it and was just using the normal `:Exit` while I was testing it. I have since resolved this, so check out the new one and let me know.

**Comment by ohadschn** [comment]
> DOH! I had actually implemented a `:Failed_Download` function previously, but forget to link it and was just using the normal `:Exit` while I was testing it. I have since resolved this, so check out the new one and let me know.

Works great now, thanks!

**Comment by ScriptTiger** [comment]
And thank you!
