### ISSUE TITLE
Use Invoke-WebRequest instead of Start-BitsTransfer when PowerShell is available

### ISSUE THREAD

**Issue by ohadschn** [ScriptTiger/Unified-Hosts-AutoUpdate#47]
If PowerShell isn't available `BITSAdmin` is a great idea, but when it is, relying on the BITS service is counterproductive:

1. If you have PowerShell installed, `Invoke-WebRequest` will always be available (it's a core part of PowerShell). However `Start-BitsTransfer` might not work if the BITS service is not up and running (or even enabled).
1. Even when BITS is enabled, it is a real potential point of failure - I am 99% sure it is the cause of my jobs failing every other night (will only know for sure now that we have error logs), and I am just as sure that `Invoke-WebRequest` would have worked 100% of them. Just now, I disabled my network, re-enabled it, and saw this in the logs: `Start-BitsTransfer : The job was paused because there is an active Game Mode recipient that isn't the job's owner. The job will resume once the Game Mode recipient loses input focus or is closed.` The bottom line is that `Invoke-WebRequest` is extremely simple, straightforward and far far more mainstream, and thus battle-tested (at least when called from PowerShell) - you would never get such weird error cases there.

Reference: https://superuser.com/questions/362152/native-alternative-to-wget-in-windows-powershell

**Comment by ScriptTiger** [comment]
Check the latest and let me know.

**Comment by ohadschn** [comment]
Looks great!

**Comment by ScriptTiger** [comment]
To be honest, I actually prefer BITS, but using built-in cmdlets undeniably does remove some complexity and hassle.
