### ISSUE TITLE
Specify log location (or instructions for enabling logging) in error messages

### ISSUE THREAD

**Issue by ohadschn** [ScriptTiger/Unified-Hosts-AutoUpdate#48]
Something that might have gotten lost in the other thread about logging, how about specifying the location of the log file in error messages? I feel it's a fair compromise between automatically enabling logs (which you wish to avoid) and helping the users debug issues themselves.

Something like this:
`Error: could not download XYZ (consult the log file for more information: C:\UHA\log.txt)`

Or in case logging was not enabled:
`Error: could not download XYZ (to enable logging add '/log' as the first parameter to the script)`

(I figure this is mostly relevant to quiet/task/`msg` errors, as a user running the script interactively can see the lines on the screen anyway)

**Comment by ScriptTiger** [comment]
Just pushed a commit for this, check it out and let me know. Since it's a non-critical update and no core functionality has changed, just some dialog, I did not increment the version for this and I'll push it out together with a future release.

I'll also note that I have been maintaining the readme after every update, so it also includes information on logging, etc. However, I do need to seriously take some time later and make more clear section headers and clean it up a bit, etc.

**Comment by ohadschn** [comment]
Looks good, though I would add to the message the location of the actual log file in case `/log` was specified (just a small convenience so you can open up that file directly rather than hunt for its location in the arguments / README).

BTW, regarding releases, you might want to consider creating a proper [GitHub release](https://github.com/ScriptTiger/Unified-Hosts-AutoUpdate/releases) each time you increment the VERSION :)

**Comment by ScriptTiger** [comment]
> Looks good, though I would add to the message the location of the actual log file in case /log was specified (just a small convenience so you can open up that file directly rather than hunt for its location in the arguments / README).

Check the latest and let me know. While testing, please confirm you can still open your hosts file with notepad++ after the script finishes normally, and please also confirm you can open the log file using notepad++ when an error occurs.

> BTW, regarding releases, you might want to consider creating a proper GitHub release each time you increment the VERSION :)

There is currently no benefit to using GitHub releases. My script repository already works out of the box and doesn't include any binaries or additional release notes beyond the standard readme, so no additional packages are needed beyond the master archive. The only reason for using this would be if someone else using the GitHub API was monitoring for releases to import my files. Currently the only project importing my files is Chocolatey, but they don't require releases and are importing the master archive directly.

Are you just wanting releases so you can stop watching my issues and only track releases? If so, I also don't get any benefit in losing your watchful eye :P

**Comment by ohadschn** [comment]
> Check the latest and let me know. While testing, please confirm you can still open your hosts file with notepad++ after the script finishes normally, and please also confirm you can open the log file using notepad++ when an error occurs.

Everything works great! I do see this in the console though, which might confuse people (since it *is* working): `File type 'Applications\notepad++.exe' not found or no open command associated with it`

> Are you just wanting releases so you can stop watching my issues and only track releases? If so, I also don't get any benefit in losing your watchful eye :P

I would have thought escaping my watchful eye would be a good thing ;)

PS AFAIK you can only watch, in which case you see issues as well as releases, or not watch, in which case you see neither

**Comment by ScriptTiger** [comment]
> Everything works great! I do see this in the console though, which might confuse people (since it is working): File type 'Applications\notepad++.exe' not found or no open command associated with it

Just cleaned this up, check it again.

> PS AFAIK you can only watch, in which case you see issues as well as releases, or not watch, in which case you see neither

https://help.github.com/en/github/receiving-notifications-about-activity-on-github/watching-and-unwatching-releases-for-a-repository

**Comment by ohadschn** [comment]
> Just cleaned this up, check it again.

Looks good!

BTW, not that it matters much, but what's the reason to pop up the `msg` in non-quiet (interactive) mode?

**Comment by ScriptTiger** [comment]
> BTW, not that it matters much, but what's the reason to pop up the msg in non-quiet (interactive) mode?

It shouldn't be. Quiet mode is when you send the URL argument to the script. Are you sure it was in quiet mode?

**Comment by ohadschn** [comment]
Just emulated an error in interactive (non-quiet) mode and the `msg` didn't pop up, so I was probably mistaken. All looks well!

**Comment by ScriptTiger** [comment]
No worries. Closing this one.
