### ISSUE TITLE
Possibility to complete scheduled task before script detects it has begun

### ISSUE THREAD

**Issue by ghost** [ScriptTiger/Unified-Hosts-AutoUpdate#50]
Related to our discussion about the usage of the lock file, I came across another small problem. First, to describe the procedure to replicate the fault:

Have the scheduled task set up and working like the gold that it is.
Run the batch file manually from a command prompt.
Receive the prompt stating that you already have a scheduled task and would you like to run it. Press 'Y' to run the task.
Task runs, exits and cleans up after itself, before the script detects that it is running.
(This occurs because the script waits 5 seconds for the cache directory to be created, and then again because it waits 5 seconds for it to be removed. If the script has nothing to update, on a nice fast NVMe drive and such, 5 seconds is about 4.9 seconds longer than it needs  ;) )
Script then sits there indefinitely waiting for the task to run.
CTRL+C to terminate the batch file, leaving temp files (user directory cache, not system cache) in place because it never gets to clean up from the manual run.

Since I feel like I created too much work for you already today, I threw together this attempt which seems to be working nicely. It's quite possibly an abomination to please feel free to discard it for a superior approach. I just wanted to contribute something more productive than "Hey I broke it" for a change ;)

    rem Function for running a scheduled task from script before exiting
    :Run
    rem Lock the running script from being replaced by an update during the triggered task
    rem Unlock later and replace running script with update if exists before exit
    echo "%LOG:"=%">"%LOCK%"
    call :Echo "Activating update task..."
    set TIMER=0

    schtasks /run /tn "%TN%"
    if not exist "%SCACHE%" goto Run_Wait_Start
    goto Run_Running

    :Run_Wait_Start
    timeout /t %TIMER% /nobreak > nul
    if not exist "%SCACHE%" (
    	set /a !TIMER!+1
    	goto Run_Wait_Start
    )
    
    :Run_Running
    call :Echo "Update task is running..."
    set TIMER=0

    :Run_Wait_Stop
    timeout /t %TIMER% /nobreak > nul
    if not exist "%SCACHE%" (
    	call :Echo "Update task has completed"
    	set TASK=3
    	del /q "%LOCK%"
    	goto View_Hosts
    )
    set /a !TIMER!+1
    goto Run_Wait_Stop

Edit: I derped and pasted the wrong version, it's no big change

**Comment by ghost** [comment]
Just to briefly explain: This is just a replacement for the existing :Run subroutine. Rather than checking after 5 seconds, it checks immediately, and then repeats the check in increments of time increasing by 1 second each check. I borrowed the implementation from the download retry mechanism to try and keep things consistent. I left some line breaks there so it's easier to digest but I realise they are not consistent with your coding style so please do remove them as needed.

It would probably be good practice to have some sort of time-out in case it waits for too long (ie, when %TIMER% gets too big), but I don't know the error handling of this script so well so ... Perhaps I shouldn't mess with that.

**Comment by ScriptTiger** [comment]
@xcasxcursex, in this case I will definitely take your suggestions under advisement since you obviously did put a lot of effort into it, but I just pushed some much simpler changes that maybe you can take a look at first and let me know if they work for you.

**Comment by ghost** [comment]
Hahaha well it wasn't too much effort since I'm older than dirt batch scripts aren't new to me, however I am guilty of just accepting your script as "magic" and not having taken enough time to learn how it works.... Which of course resulted in my making an abomination of the patch. Your way, is far more elegant, as I expected :)

Works like a charm of course. I'll go ahead and close this one since (despite appearances) I'm really trying to not cause any more work for you. 

One last note: The "say thanks" button on the front page gives me a 404.... SO.... 

 **### Thanks!!!!!**

**Comment by ScriptTiger** [comment]
> Hahaha well it wasn't too much effort since I'm older than dirt batch scripts aren't new to me, however I am guilty of just accepting your script as "magic" and not having taken enough time to learn how it works.... Which of course resulted in my making an abomination of the patch. Your way, is far more elegant, as I expected :)

LOL, I had kind of guessed your age when you used the word "subroutine," it's definitely been a few decades since I've heard that word used in practice.

> Works like a charm of course. I'll go ahead and close this one since (despite appearances) I'm really trying to not cause any more work for you.

Give me all the work you want, I'm honored to have so many experts applying their expertise to a humble batch file.

> One last note: The "say thanks" button on the front page gives me a 404

Thanks for that news. I just checked saythanks.io, apparently they only accept SSO now. When I originally registered with them I registered a local account on their website. I just registered an SSO there now and need to update all my "Say Thanks!" links. Thanks again for the update!
