### ISSUE TITLE
Wifi connection problem 

### ISSUE THREAD

**Issue by ExtraHighTension** [ScriptTiger/Unified-Hosts-AutoUpdate#56]
The script ran successfully and the basic ad-blocking features are all working. The only issue is that everytime I restart the pc, the network manager shows wifi has no internet acess and windows troubleshooter cannot identify the issue. I have to manually run the host updater script again and as soon as it enters the interactive offline mode, internet's back. I have disabled the auto updating hosts and startup of the script.

**Comment by anjannair** [comment]
I am facing a similar issue

**Comment by ScriptTiger** [comment]
Are you using a compression level?

**Comment by anjannair** [comment]
@ScriptTiger I was using the default level 1 compression

**Comment by ScriptTiger** [comment]
Please try a compression level of 9 and see if that helps.

**Comment by ScriptTiger** [comment]
@ExtraHighTension and @anjannair, if you continue to experience issues after trying a compression level of 9, please run the script with logging enabled and submit your logs here for further analysis.

**Comment by ScriptTiger** [comment]
@ExtraHighTension, if compression does indeed resolve your issue, please confirm and close this issue.

**Comment by ExtraHighTension** [comment]
> @ExtraHighTension, if compression does indeed resolve your issue, please confirm and close this issue.

It's been working fine from past few days without making any changes at all.

**Comment by ScriptTiger** [comment]
> It's been working fine from past few days without making any changes at all.

Roger that. I will go ahead and close this issue then just to keep things tidy. Please feel free to reopen it or open a new one later if things start to go awry again though.
