### ISSUE TITLE
GPO question - Follow-up

### ISSUE THREAD

**Issue by killmasta93** [ScriptTiger/Unified-Hosts-AutoUpdate#66]
Haven't heard any follow-up, so going to assume this one is resolved. If not, feel free to let me know. Again, thanks for the question!

_Originally posted by @ScriptTiger in https://github.com/ScriptTiger/Unified-Hosts-AutoUpdate/issues/65#issuecomment-1153122655_

Hi sorry didn't  receive the previous email alert it was in spam, just checking it right now, as for the GPO script, the scheduled task would be configure by computer based or user based? on the GPO? 

the user that would be running the script would by system or the Domain admin?

![image](https://user-images.githubusercontent.com/13953629/173242712-e366f780-7f67-4c38-a0e8-0fb452199a2c.png)

**Comment by ScriptTiger** [comment]
> Hi sorry didn't receive the previous email alert it was in spam, just checking it right now, as for the GPO script, the scheduled task would be configure by computer based or user based? on the GPO?

There is only one hosts file on a computer. So, no matter how many users use that computer, they are all using the same hosts file. If you want the hosts file to change depending on the user, then that would be a log-in script, not a scheduled task. However, I highly recommend NOT doing that with this particular script, as there is a high potential for extreme problems. So, I would recommend just do "computer-based" scheduled tasks.

> the user that would be running the script would by system or the Domain admin?

Use the system account, and make sure all of your computer accounts have read access to the network share where the script is located.

**Comment by killmasta93** [comment]
Thank you so much for the reply,  so in the picture above would it be correct? because on the  scheduled task in the GPO for computers shows this which shows only when the user logins
![image](https://user-images.githubusercontent.com/13953629/173244837-2b9ea3d3-b663-4110-aab8-a6613cccefdc.png)

**Comment by ScriptTiger** [comment]
> Thank you so much for the reply, so in the picture above would it be correct? because on the scheduled task in the GPO for computers shows this which shows only when the user logins

Oh, sorry! I think I misunderstood your previous comment. When you are running as a system account, it will run regardless if any user has logged in or not, so that option is a bit irrelevant. That's why I said you would have to tie it to a log-in script if you wanted to make it user-based. Tasks run by the system do not interact with logged-in users unless you also choose to make the task "interactive".

**Comment by killmasta93** [comment]
thank you so much that did the trick
