### ISSUE TITLE
StevenBlack hosts Alternative RPZ non unified hosts

### ISSUE THREAD

**Issue by alsyundawy** [ScriptTiger/Unified-Hosts-AutoUpdate#68]
can i req Additional Blacklist Support rpz without unified hosts from here

https://github.com/StevenBlack/hosts/tree/master/alternates

**Comment by ScriptTiger** [comment]
The magic of Steven Black's Unified Hosts is that the Python script behind it ensures the resultant Unified Hosts files are always in a uniform format by scrubbing and filtering and sorting the sources. This enables the conversion of the data contained within the Unified Hosts files to be converted to multiple formats with a high degree of confidence over its accuracy. If you would like something "without unified hosts", I don't support any domain block lists that are not directly converted from the Unified Hosts files in some way because that work depends on that high degree of confidence.

That being said, I do already provide RPZ lists which have been converted from Steven Black's Unified Hosts files, which you can find here:

https://scripttiger.github.io/alts/

**Comment by alsyundawy** [comment]
rpz without unified hosts you have plan?

**Comment by alsyundawy** [comment]
yes but https://raw.githubusercontent.com/StevenBlack/hosts/master/alternates/fakenews-gambling-porn/hosts merger with Unified hosts but

i just need fakenews-gambling-porn list without Unified hosts , reason is in my country gov illegal to access fakenews-gambling-porn bloked using dns but ads allowed

you can grab. from here
https://github.com/alsyundawy/dnstrust-apjii/blob/main/raw/db_trustpositif.txt

**Comment by ScriptTiger** [comment]
So, what you really want to do is convert the TrustPositif block list to RPZ, not Steven Black's Unified Hosts. All of my tools focus on using hosts files as a source, but the TrustPositif list is in plain FQDN format, so they are not compatible formats.

If you want to include only the extension domains for Steven Black's Unified Hosts but not the core Unified Hosts itself, I recommend building a custom hosts file yourself using Steven Black's Python script, and then just converting it to RPZ using Hosts-BL:

https://github.com/ScriptTiger/Hosts-BL

**Comment by ScriptTiger** [comment]
@alsyundawy, is your TrustPositif list old from before Kominfo started to obfuscate the domain names? The current domain lists available from Kominfo (https://trustpositif.kominfo.go.id) are obfuscated and cannot be used for mirroring block lists. Do you know where an unobfuscated list can be found?

**Comment by ScriptTiger** [comment]
I know the current government DNS infrastructure for Indonesia is stressed and having more privately managed local DNS RPZ servers would be a huge benefit to everyone, like for large corporations or institutions housing a large number of networked machines all currently reaching to the government DNS and not privately managed ones. I'd be interested to help develop tools to help with this if you have any ideas. I am not a proponent of Internet censorship, but at least lessening the burden of the current public infrastructure would help ensure higher available of public networks. Censored Internet is better than no Internet at all.

**Comment by alsyundawy** [comment]
> @alsyundawy, is your TrustPositif list old from before Kominfo started to obfuscate the domain names? The current domain lists available from Kominfo (https://trustpositif.kominfo.go.id) are obfuscated and cannot be used for mirroring block lists. Do you know where an unobfuscated list can be found?

i have one db every day update becouse i am the one engineer from isp, so  i wanna to merger stevenblack without unified host then https://github.com/alsyundawy/dnstrust-apjii/blob/main/raw/db_trustpositif.txt is my own list from kominfo trustpositif daily email from there (always up to date)

how about rpz, my dns server ( isp when i worki) already done with your compilation rpz alt, but have unified hosts ( sure with my own modified script from here https://github.com/iffanux/trustpositif  ), then is all my customers client complain about ads blocked, why i req without unified hosts.

**Comment by ScriptTiger** [comment]
I understand. I saw you also have an issue open with Steven Black (https://github.com/StevenBlack/hosts/issues/1954), so let's wait to see if that helps. If not, it's easy to make a script or other tool to just remove the base Unified Host list from any other list by just iterating the entries and only including domains not present on the base Unified Hosts list.

Is there a way for researchers to also have access/subscribe to the daily DB update/e-mail?

**Comment by alsyundawy** [comment]
wow thx , cant wait  heheheh ....
