### ISSUE TITLE
I ran Hosts_Update.cmd on Windows 

### ISSUE THREAD

**Issue by holygamer** [ScriptTiger/Unified-Hosts-AutoUpdate#69]
I'm using Windows 7. I download the zip, extracted it then ran the Hosts_Update.cmd file. Was asked a bunch of questions then it said:
SUCCESS: Attempted to run the scheduled task "Unified Hosts AutoUpdate".
Update task is running...

After a few minutes I get a popup message saying: "Powershell failed downloading" and it gives me the attached log:
[log.txt](https://github.com/ScriptTiger/Unified-Hosts-AutoUpdate/files/9481673/log.txt)

Why can't it download powershell?

**Comment by ScriptTiger** [comment]
```
03/09/2022 @  3:18:41.60: Executing: powershell $host.version

Major  Minor  Build  Revision
-----  -----  -----  --------
2      0      -1     -1   
```

The script performs an extremely rudimentary check before deciding on whether to use PowerShell or BITS. The preferred method is PowerShell since it plays much more nicely with the script. However, the script in this case is confused, as am I, by the particular version of PowerShell you're using, which does not appear to be an official release build. I would highly recommend for your own safety to either reinstall the latest officially released version of PowerShell from a legitimate source or just uninstall it entirely if you don't need it. If this becomes a bigger problem in the future for more folks, we can consider switching the preferred method to BITS instead of PowerShell.

Let me know how it goes after you've remediated your PowerShell as detailed above.

**Comment by holygamer** [comment]
I just have Powershell 2.0 that came with Windows 7. Also using SP1. How can't it be an official release if it came with Windows?
I tried installing Windows Management Framework 5.1 which is what has the most recent Powershell but it says it's not compatible with my Windows version when trying to install it despite the requirements saying it works with Windows 7.

Will your Hosts program block ads on YouTube once I get it working?

**Comment by ScriptTiger** [comment]
> I just have Powershell 2.0 that came with Windows 7. Also using SP1. How can't it be an official release if it came with Windows?

Did you get your Windows from an official source, either directly from Microsoft or an officially authorized reseller? And if you did get it from such a source, is it an experimental version? There are actually plenty of reasons why your Windows 7 may not be an official release itself, and thus its components aren't either, for example bootlegged versions or preview builds, etc.

> I tried installing Windows Management Framework 5.1 which is what has the most recent Powershell but it says it's not compatible with my Windows version when trying to install it despite the requirements saying it works with Windows 7.

There you go. You downloaded the official Windows Management Framework 5.1 from Microsoft and even they are saying there's a problem with your Windows 7.

> Will your Hosts program block ads on YouTube once I get it working?

Yes.

**Comment by holygamer** [comment]
Thanks. Got it working now (think I downloaded the wrong version of Powershell before).

However it doesn't block ads in YouTube when Chrome is in Incognito mode. In non-incognito mode it blocks most ads on YouTube but not all ads such as an ad I got here: https://www.youtube.com/watch?v=MUWhJ_PrlyA
I also saw a popup banner ad on this video: https://www.youtube.com/watch?v=fzBCR_C26QE

I was wondering why that is?

**Comment by ScriptTiger** [comment]
The hosts file can only block domains from being resolved locally. If you're using a browser extension or other built-in feature to resolve domains remotely, such as DoH, DoT, VPN, proxy, etc., they will bypass the hosts file entirely. Make sure all such features are disabled and that all domains are resolved locally if you want to ensure the hosts file is not being bypassed.

If you want to secure your DNS traffic while also resolving locally at the same time, the easiest way is just configure tor's DNSPort on port 53 and point to that as your DNS server so your local system can talk to it directly. Or you could set up a local DNS server to middle-man between your system and tor and allow you to filter using the local DNS server. You may also want to set up tor's HTTPTunnelPort and throw a local proxy between your browser and tor for extra filtering ability from the proxy server. And then for added security, you could use an extension like the official uBlock Origin from Raymond Hill, which imports Steven's list automatically and will filter everything at the browser level. It all depends on your personal security strategy and what you feel comfortable with.

There are also some types of ads which can't be blocked at the hosts file level if the resources for the ads themselves are not coming from a uniquely identifiable domain, such as domains which are constantly changing names, domain names which are uniquely generated per each request, or are virtually being hosted on the root domain so you can't block them without blocking YouTube itself, or whatever domain we're talking about. In these cases, using more advanced filtering, like regex or other full URL pattern-based filtering and not just static domain filtering, via other means may be better, which is not possible through a hosts file which only does static domain filtering and is not even capable of wild cards, prefix matching, suffix matching, or the like, totally static.

I can't support entries of the list itself here. So, if you have further questions to that regard, I recommend opening an issue over at Steven's repo, where the list is maintained, and they can analyze the specific domains in question and let you know if it's impossible to block or if you really have discovered something new that needs to be blocked:

https://github.com/StevenBlack/hosts

**Comment by holygamer** [comment]
I've disabled all Chrome extensions and I'm not using any built-in feature to resolve domains remotely, such as DoH, DoT, VPN, proxy, etc. I don't have any system VPNs, etc. My DNS settings are also at the Windows defaults. So just wondering why not all YouTube ads are blocked? Can you help with that or do I need to contact https://github.com/StevenBlack/hosts ? Thanks

**Comment by ScriptTiger** [comment]
> Can you help with that or do I need to contact https://github.com/StevenBlack/hosts ?

For a more thorough explanation, I would recommend Steven's repo, yes.
